### ISSUE TITLE
(LOGGING) Don't work:  env RUST_LOG_exonum_info

### ISSUE THREAD

**Issue by TFOMS** [exonum/exonum-cryptoowls#51]
Hello.
If I execute this command (how in meetup): env RUST_LOG_exonum_info exonum-cryptoowls run  --node-config example/node_1_cfg.toml --db-path example/db1 --public-api-address 0.0.0.0:8200

 it will throw env: «RUST_LOG_exonum_info»: No such file or catalog.
How start up node with LOG ?

Thanks.

**Comment by vitvakatu** [comment]
@TFOMS hello. Are you using Windows?
 You need to set `RUST_LOG` environment variable to `info` value.
On Linux you just need to prepend `RUST_LOG=info` to your command. On Windows your need to set env. variable in the separate command: `set RUST_LOG=info` before starting the node.

**Comment by vitvakatu** [comment]
@TFOMS please tell if the issue was fixed for you? If not, feel free to ask.

**Comment by TFOMS** [comment]
Thanks !!! It's work !
