### ISSUE TITLE
failed to run custom build command for `serde v1.0.80`

### ISSUE THREAD

**Issue by rakhmanu** [exonum/exonum-cryptoowls#52]
Hi,
While cargo build, i bumped into the problem with downloading serde library. How to fix it to make it work?
Thanks

**Comment by vitvakatu** [comment]
@rakhmanu Hello. Could you please provide the full error message, as well as your outputs for `rustup show` command?

**Comment by rakhmanu** [comment]
i tackled with the problem

вт, 13 нояб. 2018 г. в 17:11, Ilya Bogdanov <notifications@github.com>:

**Comment by vitvakatu** [comment]
@rakhmanu I can't reproduce the issue localy. Could you please provide additional information?

**Comment by rakhmanu** [comment]
The problem was that I have tried to cargo build on flashcard so then i downloaded all libraries on my laptop and now it is working
